from talon.voice import Context, Key

ctx = Context('symbol')

keymap = {
    '(escape | randall)': Key('esc'),
    '(question [mark] | questo)': '?',
    '(minus | dash)': '-',
    'deminus': ' - ',
    'minus twice': '--',
    'plus': '+',
    'deplush': ' + ',
    'plus twice': '++',
    'tilde': '~',
    '(bang | exclamation point | clamor)': '!',
    'banquall': ' != ',
    '(dollar [sign] | dolly)': '$',
    '(downscore | crunder)': '_',
    '(semi | semicolon | sunk)': ';',
    'colon': ':',

    '(square | left square [bracket] | brackorp)': '[',
    '(rsquare | are square | right square [bracket] | brackose)': ']',
    'brax': ['[]', Key('left')],
    '(paren | left paren)': '(',
    '(rparen | are paren | right paren)': ')',
    '(brace | left brace | kirksorp)': '{',
    '(rbrace | are brace | right brace | kirkos)': '}',
    '(clangle | angle | left angle | less than)': '<',
    'declangle': ' < ',
    '(wrangle | rangle | are angle | right angle | greater than)': '>',
    'derangle': ' > ',
    'angler': ['<>', Key('left')],

    '(star | asterisk)': '*',
    '(pound | hash [sign] | octo | thorpe | number sign)': '#',
    '(percent [sign] | percy)': '%',
    'depercy': ' % ',
    'caret': '^',
    '(at sign | loco)': '@',
    '(and sign | ampersand | amper)': '&',
    'damper': ' & ',
    'scampi': ' && ',
    'crisco': [Key('right'), ' '],
    '(pipe | spike)': '|',
    'bartrap': '||',
    'goalpost': ' || ',
    'orquals': ' ||= ',

    '(dubquote | double quote | quatches)': '"',
    'coif': ['""', Key('left')],
    '(quote | quatchet)': "'",
    'posh': ["'  '", Key('left'), Key('left')],
    'triple quote': "'''",
    '(dot | period)': '.',
    'comma': ',',
    'swipe': ', ',
    '(coalgap | coal gap)': ': ',
    '(space | skoosh)': ' ',
    '[forward] slash': '/',
    'divy': ' / ',
    '(backslash | shalls)': '\\',

    '(dot dot | dotdot | doodle)': '..',
    'ellipsis': '...',
    '(enter | shock)': Key('enter'),
    '(delete | junk)': Key('backspace'),
    'spunk': Key('delete'),

    '(equals | smaqual)': '=',
    'equeft': ' = ',
    '(longqual | long qual)': ' == ',
    'trickle': ' === ',

    'coal shock': [':', Key('enter')],
    'dot js': '.js',
    '(open fat | shrocket)': ' => ',
    'glitch': ['``', Key('left')],
    'tinker': '`',
    'trinket': ['``````', Key('left'), Key('left'), Key('left'), Key('shift-enter'), Key('shift-enter'), Key('up')],

    'sinker': [Key('cmd-right ;')],
    'slurp': [Key('delete'), Key('backspace')],

    # 'shaggy': '<'+word+'>'+'</'+word+'>'+Key('left')+Key('left')+Key('left')+Key('left'),
    'shaggy': ['<></>', Key('left'), Key('left'), Key('left'), Key('left')],
    'qualcoif': ['=""', Key('left')],
    'kirk': ['{}', Key('left')],
    'kirblock': ['{}', Key('left'), Key('enter')],
}

ctx.keymap(keymap)
